name: roboshop
services:
  mongodb: 
    build: ./mongodb
    image: <docker_username>/mongodb:v1 #this is docker build
    container_name: mongodb # this is docker run -d --network roboshop joindevops/mongodb:v1
  catalogue:
    build: ./catalogue  
    image: <docker username>/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: <docker_username>/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
  user:
    build: ./user
    image: <docker_username>/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"

  redis:
    image: redis:7
    container_name: redis # docker run -d --name redis --network roboshop redis:7
  cart:
    build: ./cart
    image: <docker_username>/cart:v1
    container_name: cart
    environment:
     REDIS_HOST: redis
     CATALOGUE_HOST: catalogue
     CATALOGUE_PORT: 8080
    depends_on:
      - redis
      - catalogue
  mysql:
    build: ./mysql
    image: <docker_username>/mysql:v1
    container_name: mysql
    command: 
      --mysql_native_password= ON
      --innodb-lock_wait_timeout=120
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
  shipping:
    build: ./shipping
    image: <docker_username>/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql
    depends_on:
      - mysql
      - cart


    
networks: 
  default: # all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this n/w
